apiVersion: apps/v1
kind: Deployment
metadata:
  name: lfa-replicate
  labels:
    app: lfa-replicate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lfa-replicate
  template:
    metadata:
      labels:
        app: lfa-replicate
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
    spec:
      containers:
      - name: mirror
        image: slaclab/rubin-lfa-replicate:latest
        env:
        - name: MINIO_LOOP_TIME
          value: "600"
        - name: MINIO_SOURCE_URL
          valueFrom:
            secretKeyRef:
              name: summit-s3
              key: endpoint-url
        - name: MINIO_SOURCE_BUCKET
          valueFrom:
            secretKeyRef:
              name: summit-s3
              key: bucket
        - name: MINIO_SOURCE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: summit-s3
              key: client-id
        - name: MINIO_SOURCE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: summit-s3
              key: secret-key
        - name: MINIO_TARGET_URL
          valueFrom:
            secretKeyRef:
              name: usdf-s3
              key: endpoint-url
        - name: MINIO_TARGET_BUCKET
          valueFrom:
            secretKeyRef:
              name: usdf-s3
              key: bucket
        - name: MINIO_TARGET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: usdf-s3
              key: client-id
        - name: MINIO_TARGET_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: usdf-s3
              key: secret-key
        volumeMounts:
        - mountPath: /root/.mc
          name: config
      volumes:
      - name: config
        emptyDir:
          sizeLimit: 10Mi

